# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e60918ab23ac2754878ec03d877213896b424af1ec72673f4144dc79a831086c3435de7faa1c5c12f65296d4fdeadfce8e01e828ac7fac08a27763af65901ec

test:
  secret_key_base: b07b2df2302672731659f44fd1a044d539aab9a5406bc4fd295d0881df809b207cf98584cbfffd5d3a1d3b7c89cbc0517fd6f63af39874b617131c0c410474c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
